# -*- coding: utf-8 -*-
"""HW2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hG-FeKhrVAaj_7m1x9Th6dLvGx-eHQaE

# HW#2
 My name is **Arvin Azad**.
 My current major is ***Computer Science and research***.
 I am currently enrolled in FarmingDale state College [link](https://www.farmingdale.edu)
 
  I Enjoy playing videog games on my pc. The games I like are:
 1. Team Fortress 2.
 2. Left 4 Dead 2
 3. Overwatch
 4. Crypt of the necrodancer
 5. Undertale
 6. Genshin Impact
 7. SCP Secret labratory.

The career That I hope I gain from my major is to become a ***game developer***.

When I was in Highschool, I used to play a ton of sports and other physical activities. Some of them being:
1. Basketball
2. Soccerball
3. Baseball
4. Hockey.
5. Karate.
6. Golf
7. Track
8. Bowling.
9. Table Tennis.
"""

